#!/usr/bin/env bash
# install nginx, listen to port 80, return page
# ./0-transfer_file ./1-install_nginx_web_server 34.138.234.27 ubuntu ~/.ssh/holberton.pub
sudo apt update
sudo apt install -y nginx 
echo "Holberton School" > /var/www/html/index.html
service nginx restart
