#!/usr/bin/env bash
# redirect to 301
sudo apt update
sudo apt install -y nginx 
echo 'Holberton School' > /var/www/html/index.html
sed -i '/server_name _/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
service nginx restart
