#!/usr/bin/env bash
#configure web-02 to be the same as web-01 and add headers
sudo apt-get -y update
sudo apt-get -y install nginx
mkdir -p /var/www/html
echo "Holberton School" >> "/var/www/html/index.html"
sudo sed -i "25i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx reload
sudo service nginx restart
