#!/usr/bin/env bash
#installs HAproxy and configures to serve as load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "
frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes
backend backendnodes
    balance roundrobin
    server 2656-web-01 34.139.127.8:80 check
    server 2656-web-02 34.138.234.27:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy reload
sudo service haproxy restart
