#!/bin/bash
# Displays luck
i=1
while [ $i -le 11 ]
do
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ "$i" == 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((i++))
done
exit 0
