#!/usr/bin/env bash
# install ufw, block all incoming traffic except 22, 443, 80
sudo apt instal ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow OpenSSH
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
