#!/usr/bin/env bash
# configures Ubuntu server so that localhost resolves to 127.0.0.2 and more
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo '8.8.8.8 facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
