#!/usr/bin/env bash
# ssh config file to login without needing a password
Host holberton
    HostName 34.138.173.41
    User ubuntu
    Port 22
    IdentityFile ~/.ssh/holberton
    PawordAuthentication   yes
    PublicKeyAuthentication   yes
