#!/usr/bin/env bash
# ssh config file to login without needing a password
Host holberton
    HostName 34.139.127.8
    User ubuntu
    Port 22
    IdentityFile ~/.ssh/holberton
    PawordAuthentication   no
    PublicKeyAuthentication   yes
